spring:
  # 로컬 개발용 MySQL (loclx 터널로 data 인스턴스 mysql 접근)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://us.loclx.io:23453/sofit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:13306/sofit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 로컬 개발용 Redis (loclx 터널로 data 인스턴스 redis 접근)
  data:
    redis:
      host: localhost
      port: 16379
